language: node_js
sudo: required
node_js:
  - "9"
install:
  - npm install
before_script:
  - webdriver-manager update
  - nohup webdriver-manager start --detach
  - npm run pretest
script:
  - npm test
