language: node_js
sudo: required
node_js:
  - "9"
install:
  - npm install
script:
  - npm run protractor-runner
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
