language: node_js
sudo: required
node_js:
  - "8"
  - "9"
  
install:
  - npm install
  
before_script:
  - webdriver-manager update && webdriver-manager start
  - npm run pretest

script:
  - npm test
